version: '3'

services:
  nginx-proxy:
    image: docker.io/nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/:/etc/nginx/certs/:ro
